#include<stdio.h>
#include<conio.h>
main()
{ int n,a=1,b=2,c=3,d=4,e=5,f=6,g=7,h=8,i=9,j=10;
clrscr();
printf("enter your namber:");
scanf("%d,",&n);
printf("\n\n");
printf("%d*%d=%d\n",n,a,n*a);
printf("%d*%d=%d\n",n,b,n*b);
printf("%d*%d=%d\n",n,c,n*c);
printf("%d*%d=%d\n",n,d,n*d);
printf("%d*%d=%d\n",n,e,n*e);
printf("%d*%d=%d\n",n,f,n*f);
printf("%d*%d=%d\n",n,g,n*g);
printf("%d*%d=%d\n",n,h,n*h);
printf("%d*%d=%d\n",n,i,n*i);
printf("%d*%d=%d\n",n,j,n*j);
getch();

}